FROM ghcr.io/soham2560/humble:latest

# Add the following labels
LABEL org.opencontainers.image.description="ROS2 Humble + ROS2 Harmonic + ROS2 Control"
LABEL org.opencontainers.image.title="ROS2_TUTORIAL"
LABEL org.opencontainers.image.vendor="Soham Patil"
LABEL org.opencontainers.image.source="https://github.com/soham2560/DockerForROS2Development"
LABEL maintainer="sohampatil45939@gmail.com"
LABEL org.opencontainers.image.licenses="MIT"

# handle default shell
SHELL ["/bin/bash", "-c"]